# Generated by Django 5.2 on 2025-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('recipient', 'Recipient'), ('organization', 'Organization')], default='organization', max_length=12),
        ),
    ]
