# Generated by Django 5.2 on 2025-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web3auth", "0002_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("recipient", "Recipient"),
                    ("organization", "Organization"),
                    ("both", "Both"),
                ],
                default="organization",
                max_length=12,
            ),
        ),
    ]
