# Generated by Django 5.2 on 2025-04-30 14:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
        ("user_profile", "0004_alter_organizationprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payroll",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="user",
        ),
        migrations.AddField(
            model_name="payroll",
            name="batch_reference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payroll",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="organization",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to="user_profile.organizationprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payroll",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="recipient",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="user_profile.recipientprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["batch_reference"], name="payroll_pay_batch_r_d942fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(fields=["status"], name="payroll_pay_status_465a76_idx"),
        ),
    ]
