# Generated by Django 5.2 on 2025-05-15 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_alter_payroll_options_remove_payroll_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="amount",
            field=models.BigIntegerField(
                help_text="Amount in smallest currency unit (e.g., cents for USD)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
