# Generated by Django 5.2 on 2025-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientprofile",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipientprofile",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipientprofile",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("on_leave", "On Leave")],
                default="active",
                max_length=30,
            ),
        ),
    ]
