# Generated by Django 5.2 on 2025-04-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0003_recipientprofile_position_recipientprofile_salary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="recipientprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="recipientprofile",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
