# Generated by Django 5.2 on 2025-05-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_alter_recipientprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipientprofile",
            unique_together=set(),
        ),
    ]
