# Generated by Django 5.2 on 2025-05-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("recipientAdded", "Recipient Added"),
                    ("recipientRemoved", "Recipient Removed"),
                    ("recipientUpdated", "Recipient Updated"),
                    ("organizationUpdated", "Organization Updated"),
                    ("organizationAdded", "Organization Added"),
                    ("organizationRemoved", "Organization Removed"),
                    ("login", "Login"),
                    ("payrollCreated", "Payroll Created"),
                    ("payrollUpdated", "Payroll Updated"),
                    ("payrollPaid", "Payroll Paid"),
                    ("payrollDeleted", "Payroll Deleted"),
                ],
                max_length=100,
            ),
        ),
    ]
